---
apiVersion : autoscaling/v2
kind : HorizontalPodAutoscaler
metadata :
  name : ghpa
spec :
  scaleTargetRef :
    apiVersion : apps/v1
    kind : Deployment
    name : grocerre
  minReplicas : 3
  maxReplicas : 6
  metrics :
    - type : Resource
      resource :
        name : cpu
        target :
          type : Utilization
          averageUtilization : 60


